name: test
channels:
- conda-forge
- defaults
dependencies:
- python=3.*
- ipython
- jupyter
- notebook
- ipykernel
- numpy
- pandas
- fiona
- shapely
- rtree
- pyproj>=2.0
- codecov
- coverage
- flake8
- pytest
- sphinx
- matplotlib
- numpydoc
- sphinx-copybutton
- sphinx_rtd_theme
- pip
- pip:
    - https://github.com/aleaf/gis-utils/zipball/master
#    - gis-utils
